/**
 * Bechde Listings API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Money } from './money';


export interface ListingCreate { 
    title: string;
    description: string;
    price: Money;
    category: ListingCreate.CategoryEnum;
    city: string;
    lat?: number;
    lon?: number;
}
export namespace ListingCreate {
    export const CategoryEnum = {
        Electronics: 'electronics',
        Furniture: 'furniture',
        Vehicles: 'vehicles',
        Other: 'other'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
}


