/**
 * Bechde Listings API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Money } from './money';


export interface Listing { 
    title: string;
    description: string;
    price: Money;
    category: Listing.CategoryEnum;
    city: string;
    lat?: number;
    lon?: number;
    id: string;
    status: Listing.StatusEnum;
    slug: string;
    publishedAt?: string;
}
export namespace Listing {
    export const CategoryEnum = {
        Electronics: 'electronics',
        Furniture: 'furniture',
        Vehicles: 'vehicles',
        Other: 'other'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
    export const StatusEnum = {
        Draft: 'draft',
        Published: 'published',
        Unpublished: 'unpublished'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


