/**
 * Bechde Listings API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Money { 
    amount: number;
    currency: Money.CurrencyEnum;
}
export namespace Money {
    export const CurrencyEnum = {
        Usd: 'USD',
        Inr: 'INR',
        Eur: 'EUR'
    } as const;
    export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];
}


