/**
 * Bechde Payments API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentsCheckoutSessionPostRequest { 
    listingId: string;
    placementType: PaymentsCheckoutSessionPostRequest.PlacementTypeEnum;
}
export namespace PaymentsCheckoutSessionPostRequest {
    export const PlacementTypeEnum = {
        Featured: 'featured',
        Boosted: 'boosted'
    } as const;
    export type PlacementTypeEnum = typeof PlacementTypeEnum[keyof typeof PlacementTypeEnum];
}


