/**
 * Bechde Users API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsersMePatchRequest { 
    displayName?: string;
    city?: string;
    phone?: string;
}

